# Compile and link real emitted C++, not just text assertions.
set(args -S "${SOURCE_DIR}" -B "${BINARY_DIR}" -G "${GENERATOR}")
if(DEFINED PLATFORM AND NOT PLATFORM STREQUAL "")
    list(APPEND args -A "${PLATFORM}")
endif()
if(DEFINED TOOLSET AND NOT TOOLSET STREQUAL "")
    list(APPEND args -T "${TOOLSET}")
endif()
list(APPEND args "-DCMAKE_CXX_COMPILER=${CXX_COMPILER}" "-DCMAKE_BUILD_TYPE=${CONFIG}")
execute_process(COMMAND "${CMAKE_COMMAND}" ${args} RESULT_VARIABLE rc)
if(NOT rc EQUAL 0)
    message(FATAL_ERROR "Generated project configuration failed: ${rc}")
endif()
execute_process(COMMAND "${CMAKE_COMMAND}" --build "${BINARY_DIR}" --config "${CONFIG}" --parallel 1 RESULT_VARIABLE rc)
if(NOT rc EQUAL 0)
    message(FATAL_ERROR "Generated C++ compile/link failed: ${rc}")
endif()
set(exe "${BINARY_DIR}/generated_compile_test${EXE_SUFFIX}")
if(EXISTS "${BINARY_DIR}/${CONFIG}/generated_compile_test${EXE_SUFFIX}")
    set(exe "${BINARY_DIR}/${CONFIG}/generated_compile_test${EXE_SUFFIX}")
endif()
execute_process(COMMAND "${exe}" WORKING_DIRECTORY "${BINARY_DIR}" RESULT_VARIABLE rc)
if(NOT rc EQUAL 0)
    message(FATAL_ERROR "Generated runtime smoke test failed: ${rc}")
endif()
