#pragma once

#include <cstdint>
#include <string>

namespace dcrecomp::sh4 {

enum class Opcode {
    Unknown,

    // Control / system
    Nop,
    Rts,
    Rte,
    Bra,
    Bsr,
    Bt,
    Bf,
    BtS,
    BfS,
    Braf,
    Bsrf,
    Jmp,
    Jsr,
    ClrT,
    SetT,
    ClrS,
    SetS,
    ClrMac,
    Sleep,
    LdTlb,
    Trapa,

    // Cache/store-queue control. Cache effects are abstracted by the generated
    // runtime; PREF retains a hook for Dreamcast store-queue integration later.
    Pref,
    MovcaL,
    Ocbi,
    Ocbp,
    Ocbwb,

    // Integer / logical
    MovImm,
    MovReg,
    AddImm,
    AddReg,
    Addc,
    Addv,
    SubReg,
    Subc,
    Subv,
    Neg,
    Negc,
    CmpEqImm,
    CmpEq,
    CmpStr,
    CmpHs,
    CmpGe,
    CmpHi,
    CmpGt,
    CmpPz,
    CmpPl,
    TstReg,
    AndReg,
    XorReg,
    OrReg,
    Not,
    TstImm,
    AndImm,
    XorImm,
    OrImm,
    Dt,
    Div0U,
    Div0S,
    Div1,
    MulL,
    MuluW,
    MulsW,
    DmuluL,
    DmulsL,
    SwapB,
    SwapW,
    Xtrct,

    // Shifts / rotates / extension
    Shll,
    Shlr,
    Shal,
    Shar,
    Shll2,
    Shlr2,
    Shll8,
    Shlr8,
    Shll16,
    Shlr16,
    Rotl,
    Rotr,
    Rotcl,
    Rotcr,
    Shld,
    Shad,
    ExtuB,
    ExtuW,
    ExtsB,
    ExtsW,

    // Loads / stores
    MovBStore,
    MovWStore,
    MovLStore,
    MovBLoad,
    MovWLoad,
    MovLLoad,
    MovBPredec,
    MovWPredec,
    MovLPredec,
    MovBPostinc,
    MovWPostinc,
    MovLPostinc,
    MovBDispStore,
    MovWDispStore,
    MovBDispLoad,
    MovWDispLoad,
    MovLDispStore,
    MovLDispLoad,
    MovBIndexedStore,
    MovWIndexedStore,
    MovLIndexedStore,
    MovBIndexedLoad,
    MovWIndexedLoad,
    MovLIndexedLoad,
    MovWPcRel,
    MovLPcRel,
    Mova,
    Movt,

    // Special registers commonly emitted by GCC prologues/epilogues
    StsPr,
    StsLPr,
    LdsPr,
    LdsLPr,

    // Additional SH-4 special-register transfers used heavily by GCC/KallistiOS.
    StsMach,
    StsMacl,
    StsFpul,
    StsFpscr,
    LdsMach,
    LdsMacl,
    LdsFpul,
    LdsFpscr,

    // Control-register transfers (SH-4 system state).
    StcSr, StcGbr, StcVbr, StcSsr, StcSpc, StcSgr, StcDbr, StcBank,
    StcLSr, StcLGbr, StcLVbr, StcLSsr, StcLSpc, StcLSgr, StcLDbr, StcLBank,
    LdcSr, LdcGbr, LdcVbr, LdcSsr, LdcSpc, LdcSgr, LdcDbr, LdcBank,
    LdcLSr, LdcLGbr, LdcLVbr, LdcLSsr, LdcLSpc, LdcLSgr, LdcLDbr, LdcLBank,

    // Stack forms of system-register transfers generated by GCC.
    StsLMach, StsLMacl, StsLFpul, StsLFpscr,
    LdsLMach, LdsLMacl, LdsLFpul, LdsLFpscr,

    // Floating-point arithmetic / compare. FPSCR.PR chooses single vs double
    // precision for FADD/FSUB/FMUL/FDIV/FCMP; FMAC is single precision only.
    Fadd,
    Fsub,
    Fmul,
    Fdiv,
    FcmpEq,
    FcmpGt,
    Fmac,

    // Floating-point unary/conversion/vector operations.
    Fsts,
    Flds,
    Float,
    Ftrc,
    Fneg,
    Fabs,
    Fsqrt,
    Fsrra,
    Fldi0,
    Fldi1,
    Fcnvsd,
    Fcnvds,
    Fipr,
    Ftrv,
    Fsca,
    Frchg,
    Fschg,

    // Floating-point register/memory moves (32-bit path; FPSCR.SZ=0).
    FmovLoad,
    FmovLoadPostInc,
    FmovStore,
    FmovStorePreDec,
    FmovReg,
    FmovIndexedLoad,
    FmovIndexedStore,

    // Atomic byte test/set.
    TasB,
};

struct Instruction {
    Opcode opcode{Opcode::Unknown};
    std::uint16_t raw{};
    std::uint32_t address{};
    std::uint8_t rn{};
    std::uint8_t rm{};
    std::int32_t immediate{};
    std::uint32_t target{};
    std::uint32_t effective_address{};
    bool has_delay_slot{};
};

Instruction decode(std::uint16_t raw, std::uint32_t address);
std::string to_string(const Instruction& instruction);
bool is_known(const Instruction& instruction);

} // namespace dcrecomp::sh4
